# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ars11/Desktop/temprjcts

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ars11/Desktop/temprjcts

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ars11/Desktop/temprjcts/CMakeFiles /home/ars11/Desktop/temprjcts//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ars11/Desktop/temprjcts/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main.app

# Build rule for target.
main.app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main.app
.PHONY : main.app

# fast build rule for target.
main.app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.app.dir/build.make CMakeFiles/main.app.dir/build
.PHONY : main.app/fast

#=============================================================================
# Target rules for targets named files.app

# Build rule for target.
files.app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 files.app
.PHONY : files.app

# fast build rule for target.
files.app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/files.app.dir/build.make CMakeFiles/files.app.dir/build
.PHONY : files.app/fast

#=============================================================================
# Target rules for targets named struct.app

# Build rule for target.
struct.app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 struct.app
.PHONY : struct.app

# fast build rule for target.
struct.app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/struct.app.dir/build.make CMakeFiles/struct.app.dir/build
.PHONY : struct.app/fast

#=============================================================================
# Target rules for targets named enum.app

# Build rule for target.
enum.app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 enum.app
.PHONY : enum.app

# fast build rule for target.
enum.app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/enum.app.dir/build.make CMakeFiles/enum.app.dir/build
.PHONY : enum.app/fast

#=============================================================================
# Target rules for targets named trycatch.app

# Build rule for target.
trycatch.app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trycatch.app
.PHONY : trycatch.app

# fast build rule for target.
trycatch.app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trycatch.app.dir/build.make CMakeFiles/trycatch.app.dir/build
.PHONY : trycatch.app/fast

#=============================================================================
# Target rules for targets named math.app

# Build rule for target.
math.app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 math.app
.PHONY : math.app

# fast build rule for target.
math.app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.app.dir/build.make CMakeFiles/math.app.dir/build
.PHONY : math.app/fast

#=============================================================================
# Target rules for targets named class.app

# Build rule for target.
class.app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 class.app
.PHONY : class.app

# fast build rule for target.
class.app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class.app.dir/build.make CMakeFiles/class.app.dir/build
.PHONY : class.app/fast

#=============================================================================
# Target rules for targets named construct_this.app

# Build rule for target.
construct_this.app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 construct_this.app
.PHONY : construct_this.app

# fast build rule for target.
construct_this.app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/construct_this.app.dir/build.make CMakeFiles/construct_this.app.dir/build
.PHONY : construct_this.app/fast

#=============================================================================
# Target rules for targets named friendly_functions.app

# Build rule for target.
friendly_functions.app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 friendly_functions.app
.PHONY : friendly_functions.app

# fast build rule for target.
friendly_functions.app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/friendly_functions.app.dir/build.make CMakeFiles/friendly_functions.app.dir/build
.PHONY : friendly_functions.app/fast

#=============================================================================
# Target rules for targets named friendly_class.app

# Build rule for target.
friendly_class.app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 friendly_class.app
.PHONY : friendly_class.app

# fast build rule for target.
friendly_class.app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/friendly_class.app.dir/build.make CMakeFiles/friendly_class.app.dir/build
.PHONY : friendly_class.app/fast

class.o: class.cpp.o
.PHONY : class.o

# target to build an object file
class.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class.app.dir/build.make CMakeFiles/class.app.dir/class.cpp.o
.PHONY : class.cpp.o

class.i: class.cpp.i
.PHONY : class.i

# target to preprocess a source file
class.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class.app.dir/build.make CMakeFiles/class.app.dir/class.cpp.i
.PHONY : class.cpp.i

class.s: class.cpp.s
.PHONY : class.s

# target to generate assembly for a file
class.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class.app.dir/build.make CMakeFiles/class.app.dir/class.cpp.s
.PHONY : class.cpp.s

construct_this.o: construct_this.cpp.o
.PHONY : construct_this.o

# target to build an object file
construct_this.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/construct_this.app.dir/build.make CMakeFiles/construct_this.app.dir/construct_this.cpp.o
.PHONY : construct_this.cpp.o

construct_this.i: construct_this.cpp.i
.PHONY : construct_this.i

# target to preprocess a source file
construct_this.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/construct_this.app.dir/build.make CMakeFiles/construct_this.app.dir/construct_this.cpp.i
.PHONY : construct_this.cpp.i

construct_this.s: construct_this.cpp.s
.PHONY : construct_this.s

# target to generate assembly for a file
construct_this.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/construct_this.app.dir/build.make CMakeFiles/construct_this.app.dir/construct_this.cpp.s
.PHONY : construct_this.cpp.s

enum.o: enum.cpp.o
.PHONY : enum.o

# target to build an object file
enum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/enum.app.dir/build.make CMakeFiles/enum.app.dir/enum.cpp.o
.PHONY : enum.cpp.o

enum.i: enum.cpp.i
.PHONY : enum.i

# target to preprocess a source file
enum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/enum.app.dir/build.make CMakeFiles/enum.app.dir/enum.cpp.i
.PHONY : enum.cpp.i

enum.s: enum.cpp.s
.PHONY : enum.s

# target to generate assembly for a file
enum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/enum.app.dir/build.make CMakeFiles/enum.app.dir/enum.cpp.s
.PHONY : enum.cpp.s

files.o: files.cpp.o
.PHONY : files.o

# target to build an object file
files.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/files.app.dir/build.make CMakeFiles/files.app.dir/files.cpp.o
.PHONY : files.cpp.o

files.i: files.cpp.i
.PHONY : files.i

# target to preprocess a source file
files.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/files.app.dir/build.make CMakeFiles/files.app.dir/files.cpp.i
.PHONY : files.cpp.i

files.s: files.cpp.s
.PHONY : files.s

# target to generate assembly for a file
files.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/files.app.dir/build.make CMakeFiles/files.app.dir/files.cpp.s
.PHONY : files.cpp.s

friendly_class.o: friendly_class.cpp.o
.PHONY : friendly_class.o

# target to build an object file
friendly_class.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/friendly_class.app.dir/build.make CMakeFiles/friendly_class.app.dir/friendly_class.cpp.o
.PHONY : friendly_class.cpp.o

friendly_class.i: friendly_class.cpp.i
.PHONY : friendly_class.i

# target to preprocess a source file
friendly_class.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/friendly_class.app.dir/build.make CMakeFiles/friendly_class.app.dir/friendly_class.cpp.i
.PHONY : friendly_class.cpp.i

friendly_class.s: friendly_class.cpp.s
.PHONY : friendly_class.s

# target to generate assembly for a file
friendly_class.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/friendly_class.app.dir/build.make CMakeFiles/friendly_class.app.dir/friendly_class.cpp.s
.PHONY : friendly_class.cpp.s

friendly_functions.o: friendly_functions.cpp.o
.PHONY : friendly_functions.o

# target to build an object file
friendly_functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/friendly_functions.app.dir/build.make CMakeFiles/friendly_functions.app.dir/friendly_functions.cpp.o
.PHONY : friendly_functions.cpp.o

friendly_functions.i: friendly_functions.cpp.i
.PHONY : friendly_functions.i

# target to preprocess a source file
friendly_functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/friendly_functions.app.dir/build.make CMakeFiles/friendly_functions.app.dir/friendly_functions.cpp.i
.PHONY : friendly_functions.cpp.i

friendly_functions.s: friendly_functions.cpp.s
.PHONY : friendly_functions.s

# target to generate assembly for a file
friendly_functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/friendly_functions.app.dir/build.make CMakeFiles/friendly_functions.app.dir/friendly_functions.cpp.s
.PHONY : friendly_functions.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.app.dir/build.make CMakeFiles/main.app.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.app.dir/build.make CMakeFiles/main.app.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.app.dir/build.make CMakeFiles/main.app.dir/main.cpp.s
.PHONY : main.cpp.s

math.o: math.cpp.o
.PHONY : math.o

# target to build an object file
math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.app.dir/build.make CMakeFiles/math.app.dir/math.cpp.o
.PHONY : math.cpp.o

math.i: math.cpp.i
.PHONY : math.i

# target to preprocess a source file
math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.app.dir/build.make CMakeFiles/math.app.dir/math.cpp.i
.PHONY : math.cpp.i

math.s: math.cpp.s
.PHONY : math.s

# target to generate assembly for a file
math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.app.dir/build.make CMakeFiles/math.app.dir/math.cpp.s
.PHONY : math.cpp.s

struct.o: struct.cpp.o
.PHONY : struct.o

# target to build an object file
struct.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/struct.app.dir/build.make CMakeFiles/struct.app.dir/struct.cpp.o
.PHONY : struct.cpp.o

struct.i: struct.cpp.i
.PHONY : struct.i

# target to preprocess a source file
struct.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/struct.app.dir/build.make CMakeFiles/struct.app.dir/struct.cpp.i
.PHONY : struct.cpp.i

struct.s: struct.cpp.s
.PHONY : struct.s

# target to generate assembly for a file
struct.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/struct.app.dir/build.make CMakeFiles/struct.app.dir/struct.cpp.s
.PHONY : struct.cpp.s

trycatch.o: trycatch.cpp.o
.PHONY : trycatch.o

# target to build an object file
trycatch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trycatch.app.dir/build.make CMakeFiles/trycatch.app.dir/trycatch.cpp.o
.PHONY : trycatch.cpp.o

trycatch.i: trycatch.cpp.i
.PHONY : trycatch.i

# target to preprocess a source file
trycatch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trycatch.app.dir/build.make CMakeFiles/trycatch.app.dir/trycatch.cpp.i
.PHONY : trycatch.cpp.i

trycatch.s: trycatch.cpp.s
.PHONY : trycatch.s

# target to generate assembly for a file
trycatch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trycatch.app.dir/build.make CMakeFiles/trycatch.app.dir/trycatch.cpp.s
.PHONY : trycatch.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... class.app"
	@echo "... construct_this.app"
	@echo "... enum.app"
	@echo "... files.app"
	@echo "... friendly_class.app"
	@echo "... friendly_functions.app"
	@echo "... main.app"
	@echo "... math.app"
	@echo "... struct.app"
	@echo "... trycatch.app"
	@echo "... class.o"
	@echo "... class.i"
	@echo "... class.s"
	@echo "... construct_this.o"
	@echo "... construct_this.i"
	@echo "... construct_this.s"
	@echo "... enum.o"
	@echo "... enum.i"
	@echo "... enum.s"
	@echo "... files.o"
	@echo "... files.i"
	@echo "... files.s"
	@echo "... friendly_class.o"
	@echo "... friendly_class.i"
	@echo "... friendly_class.s"
	@echo "... friendly_functions.o"
	@echo "... friendly_functions.i"
	@echo "... friendly_functions.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... math.o"
	@echo "... math.i"
	@echo "... math.s"
	@echo "... struct.o"
	@echo "... struct.i"
	@echo "... struct.s"
	@echo "... trycatch.o"
	@echo "... trycatch.i"
	@echo "... trycatch.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

